# Generated by Django 3.0.8 on 2020-07-30 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200729_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 20, 55, 59, 806893)),
        ),
    ]
